apiVersion: v1
kind: Secret
metadata:
  name: devboard-secrets
  namespace: devboard-prod
type: Opaque
data:
  # NOTE: Replace this placeholder with base64-encoded "postgres://<DB_USER>:<DB_PASSWORD>@<RDS_ENDPOINT>:5432/<DB_NAME>?sslmode=require"
  POSTGRES_URL: cG9zdGdyZXM6Ly88REJfVVNFUj46PERCX1BBU1NXT1JEPkA8UkRTX0VORFBPSU5UPjo1NDMyLzxEQl9OQU1FPj9zc2xtb2RlPXJlcXVpcmU=
